### ISSUE TITLE
dropbear does not recognize riscv architecture

### ISSUE THREAD

**Issue by aurabindo** [michaeljclark/busybear-linux#6]
I cannot get dropbear to be built because of this error:
```
checking build system type... x86_64-unknown-linux-gnu
checking host system type... Invalid configuration `riscv64-linux-gnu': machine `riscv64' not recognized
configure: error: /bin/bash ./config.sub riscv64-linux-gnu failed
```
Looking at config.sub, the file does not contain any any entry for riscv arch. On the contrary, openssh has riscv64 machines entries in its `config.sub`: https://github.com/openssh/openssh-portable/blob/38e83e4f219c752ebb1560633b73f06f0392018b/config.sub#L305

Is there a patch for dropbear? How did you get it to work ?

**Comment by aurabindo** [comment]
Replaced config.guess and config.sub with a newer version

**Comment by stefanct** [comment]
E.g. via `curl 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' > config.guess`
